# Generated by Django 5.1.dev20240319090312 on 2024-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
