# Generated by Django 5.1.dev20240319090312 on 2024-03-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
