# Generated by Django 5.1.dev20240319090312 on 2024-03-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_cartitem_order_orderitem_order_items_shoppingcart_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="cart_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.cartitem",
            ),
        ),
    ]
