# Generated by Django 5.1.dev20240319090312 on 2024-03-21 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_orderitem_cart_item"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("address_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "street_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Street Address",
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Town"
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Zip Code"
                    ),
                ),
                ("county", models.CharField(max_length=255, null=True)),
                (
                    "phone_number_1",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number 1",
                    ),
                ),
                (
                    "phone_number_2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number 2",
                    ),
                ),
                (
                    "additional_details",
                    models.TextField(
                        blank=True, null=True, verbose_name="Additional Details"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "ordering": ["user", "street_address"],
            },
        ),
    ]
