# Generated by Django 5.1.dev20240319090312 on 2024-03-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("delivery_time", models.CharField(max_length=255)),
            ],
        ),
    ]
